language: php

php:
  - 5.6
  - 7.0
  - 7.1

matrix:
  fast_finish: true

before_script:
  - mkdir -p build/logs
  - mysql -e 'create database IF NOT EXISTS errorheromodule;' -uroot
  - mysql -u root errorheromodule < spec/Fixture/data/sql.sql
  - composer self-update
  - composer install --prefer-source --no-interaction
  - if [[ $TRAVIS_PHP_VERSION = 7.1 ]]; then composer global require --dev phpstan/phpstan:dev-master; fi
  - composer dump-autoload -o

script:
  - if [[ $TRAVIS_PHP_VERSION = 7.1 ]]; then ~/.composer/vendor/bin/phpstan analyse src/ --level=5; fi
  - bin/kahlan --coverage=4 --reporter=verbose --clover=build/logs/clover.xml
  - if [[ $TRAVIS_PHP_VERSION = 7.1 ]]; then bin/coveralls -v --exclude-no-stmt; fi

notifications:
    email: false
