language: php

php:
  - 5.6
  - 7.0
  - 7.1

matrix:
  fast_finish: true

before_script:
  - mysql -e 'create database IF NOT EXISTS errorheromodule;' -uroot
  - mysql -u root errorheromodule < data/sql.sql
  - composer self-update
  - composer install --prefer-source --no-interaction
  - if [[ $TRAVIS_PHP_VERSION = 7.1 ]]; then composer global require --dev phpstan/phpstan; fi
  - composer dump-autoload -o
  - if [[ $TRAVIS_PHP_VERSION = 7.1 ]]; then ~/bin/phpstan analyse src/; fi

script:
  - bin/kahlan --coverage=4 --reporter=verbose --clover=build/logs/clover.xml
  - if [[ $TRAVIS_PHP_VERSION = 7.1 ]]; then bin/coveralls -v --exclude-no-stmt; fi

notifications:
    email: false
